/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = string;
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'customerPhone' : string,
  'createdAt' : bigint,
  'deliveryTime' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface OrderRequest {
  'customerName' : string,
  'deliveryAddress' : string,
  'customerPhone' : string,
  'deliveryTime' : string,
  'items' : Array<OrderItem>,
}
export type OrderStatus = { 'preparing' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export type ProductId = bigint;
export interface ProductInput {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[ProductInput], Product>,
  'claimOwnership' : ActorMethod<[], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getOwner' : ActorMethod<[], [] | [Principal]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'isOwner' : ActorMethod<[], boolean>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[OrderRequest], Order>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];